# Site settings
title: ZeroLag C++ Reference
description: "A fast-access C++ cheatsheet for quick development. Modern, revamped, and easy to navigate."
author: "Siddharth" 
#email: your-email@example.com 

# Site URL and Base URL
url: "https://sidmegh.github.io"
baseurl: "/zerolag"

# Navigation structure (custom variable)
header_pages:
  - core.md
  - stl.md
  - modern.md

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight' # Default CSS class for highlighted code blocks
  toc_levels: 1..3 # For {{ page.table_of_contents }}

# Theme
theme: null

# SCSS/Sass settings
sass:
  style: compressed # Minify CSS in production

# Exclude from processing
exclude:
  - README.md
  - LICENSE.md

# Defaults for posts and pages
defaults:
  - scope:
      path: "" # all files in the project
    values:
      layout: "default" 